version: "3" 
services:
  kibana:
    image: kibana:6.4.2
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - default
  webserver:
    image: nginx:alpine
    container_name: nginx-web
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: default
      MYSQL_ROOT_PASSWORD: mysql_pass
    networks:
      - default

#Docker Networks
networks:
  app-network:
    driver: bridge
